
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: gcr.io/broyal-llama-demo/llama-demo/chat-app:0.1.11
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: "1"
        ports:
        - name: server-port
          containerPort: 7860
        env:
        - name: PGVECTOR_HOST
          value: "postgres-service"
        - name: TGI_HOSTNAME
          value: "gemma-tgi-service"
        - name: COLLECTION_NAME
          value: "k8s_concepts"
        - name: TGI_PORT
          value: "80"
        - name: MODEL_NAME
          value: "Gemma 7B"
        - name: SENTENCE_TRANSFORMERS_HOME
          value: "/data"
        - name: PUBSUB_SUBSCRIPTION
          value: "k8s_concepts_subscription"
        volumeMounts:
          - mountPath: /data
            name: st-data
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
      volumes:
         - name: st-data
           ephemeral:
              volumeClaimTemplate:
                metadata:
                  labels:
                    type: data-volume
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: "premium-rwo"
                  resources:
                    requests:
                      storage: 200Gi
         - name: secret-volume
           secret:
              secretName: pubsub-svc
              items:
              - key: pubsub-svc.json
                path: pubsub-svc.json
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
