apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-ingress
data:
  nginx.conf: |-
    user nginx;
    worker_processes  10;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: gcr.io/broyal-llama-demo/llama-demo/chat-app:0.1.4
        resources:
          limits:
            nvidia.com/gpu: "1"
        ports:
        - name: server-port
          containerPort: 7860
        env:
        - name: PGVECTOR_HOST
          value: "postgres-service"
        - name: TGI_HOSTNAME
          value: "mistral-7b-service"
        - name: TGI_PORT
          value: "80"
        - name: HOSTNAME
          value: "chat-app-service.default.svc.cluster.local"
        - name: MODEL_NAME
          value: "Mistral 7B"
        - name: SENTENCE_TRANSFORMERS_HOME
          value: "/data"
        volumeMounts:
          - mountPath: /data
            name: st-data
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          #runAsUser: 0
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
              #subPath: nginx.conf
              readOnly: true
      volumes:
         - name: st-data
           hostPath:
            path: /mnt/stateful_partition/kube-ephemeral-ssd/sentence-transformers
         - name: nginx-conf
           configMap:
              name: nginx-conf
              items:
                - key: nginx.conf
                  path: nginx.conf
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
