apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: chat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7860
  type: LoadBalancer