# FROM python:3.10
# FROM gcr.io/deeplearning-platform-release/base-cu113.py310
FROM nvidia/cuda:11.3.1-base-ubuntu20.04

RUN apt update
RUN apt install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.10 -y
RUN apt install python3-pip -y

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "indexer.py"]