apiVersion: v1
kind: Service
metadata:
  name: mistral-7b-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: mistral-7b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer