apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
      - name: indexer
        image: gcr.io/broyal-llama-demo/llama-demo/indexer:0.1.10
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: "1"
        env:
          - name: PGVECTOR_HOST
            value: "postgres-service"
          - name: PUBSUB_SUBSCRIPTION
            value: "k8s_concepts_subscription"
          - name: COLLECTION_NAME
            value: "k8s_concepts"
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
      volumes:
        - name: secret-volume
          secret:
            secretName: pubsub-svc
            items:
            - key: pubsub-svc.json
              path: pubsub-svc.json
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4