apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - external:
      metric:
       name: pubsub.googleapis.com|subscription|num_undelivered_messages
       selector:
         matchLabels:
           resource.labels.subscription_id: k8s_concepts_subscription
           resource.labels.project_id: broyal-llama-demo
      target:
        type: AverageValue
        averageValue: "25"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indexer