apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
spec:
  containers:
  - name: jupyter-pod
    image: jupyter/base-notebook:x86_64-python-3.10
    env:
      - name: NOTEBOOK_ARGS
        value: "--NotebookApp.allow_origin='*' --no-browser"
    ports:
      - containerPort: 8888
    volumeMounts:
        - mountPath: "/home/jovyan"
          name: jupyter-pvc-vol
    resources:
      limits:
       nvidia.com/gpu: "2"
  volumes:
    - name: jupyter-pvc-vol
      persistentVolumeClaim:
       claimName: jupyter-pvc
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: jupyter-pod
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888