apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: ml-monitor
spec:
  selector:
    matchLabels:
      server: text-generation-interface
  endpoints:
  - port: port-name
    timeout: 20s
    path: /metrics
    scheme: http
    interval: 30s
---