apiVersion: v1
kind: Namespace
metadata:
  name: ml-monitoring
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: tgi-monitor
  namespace: ml-monitoring
spec:
  selector:
    matchLabels:
      server: text-generation-interface
  endpoints:
  - port: server-port
    timeout: 20s
    path: /metrics
    scheme: http
    interval: 30s