# gcr.io/broyal-llama-demo/llama-demo/indexer

apiVersion: batch/v1
kind: Job
metadata:
  name: indexer-job
  labels:
    job: "indexer"
spec:
  template:
    spec:
      containers:
      - name: indexer-job
        image: gcr.io/broyal-llama-demo/llama-demo/indexer:0.1.9
        resources:
          limits:
            nvidia.com/gpu: "1"
        env:
          - name: PGVECTOR_HOST
            value: "postgres-service"
          - name: PUBSUB_SUBSCRIPTION
            value: "kubernetes_concepts-2"
          - name: COLLECTION_NAME
            value: "kubernetes_concepts-2"
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
      volumes:
        - name: secret-volume
          secret:
            secretName: pubsub-svc
            items:
            - key: pubsub-svc.json
              path: pubsub-svc.json
      restartPolicy: OnFailure
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      
  parallelism: 3