apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    job: "indexer"
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: busybox
        command:
        - ls
        - "-l"
        - "/etc/secret-volume"
        # resources:
        #   limits:
        #     nvidia.com/gpu: "1"
        env:
          - name: PGVECTOR_HOST
            value: "postgres"
          - name: PUBSUB_SUBSCRIPTION
            value: "kubernetes_concepts_subscription"
          - name: COLLECTION_NAME
            value: "kubernetes_concepts"
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
      volumes:
        - name: secret-volume
          secret:
            secretName: pubsub-svc
            items:
            - key: pubsub-svc.json
              path: pubsub-svc.json
      restartPolicy: OnFailure
      # nodeSelector:
      #   cloud.google.com/gke-accelerator: nvidia-l4
      
  parallelism: 3

        
