apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-2-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-2-7b
  template:
    metadata:
      labels:
        app: llama-2-7b
        server: text-generation-inference
    spec:
      containers:
      - name: llama-2-7b
        image: ghcr.io/huggingface/text-generation-inference:1.0.3
        resources:
          limits:
            cpu: "8"
            memory: "16Gi"
            nvidia.com/gpu: "1"
        ports:
        - name: server-port
          containerPort: 8080
        env:
        - name: MODEL_ID
          value: meta-llama/Llama-2-7b-chat-hf
        - name: NUM_SHARD
          value: "1"
        - name: PORT 
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes-nf4
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: l4-demo
              key: HF_TOKEN
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
         - name: dshm
           emptyDir:
              medium: Memory
         - name: data
           ephemeral:
              volumeClaimTemplate:
                metadata:
                  labels:
                    type: data-volume
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: "premium-rwo"
                  resources:
                    requests:
                      storage: 200Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
