apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: pgvector
      image: ankane/pgvector
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secretpassword"
      volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgredb
      hostPath:
        path: /mnt/stateful_partition/kube-ephemeral-ssd/postgres

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
#   labels:
#     app: postgres
# data:
#   POSTGRES_DB: postgresdb
#   POSTGRES_USER: admin
#   POSTGRES_PASSWORD: psltest
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume  # Sets PV's name
#   labels:
#     type: local  # Sets PV's type to local
#     app: postgres
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 50Gi # Sets PV Volume
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data"
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: postgres-pv-claim  # Sets name of PVC
#   labels:
#     app: postgres
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany  # Sets read and write access
#   resources:
#     requests:
#       storage: 50Gi  # Sets volume size
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres  # Sets Deployment name
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#         - name: postgres
#           image: ankane/pgvector
#           imagePullPolicy: "IfNotPresent"
#           ports:
#             - containerPort: 5432  # Exposes container port
#           envFrom:
#             - configMapRef:
#                 name: postgres-config
#           volumeMounts:
#             - mountPath: /var/lib/postgresql/data
#               name: postgredb
#       volumes:
#         - name: postgredb
#           hostPath:
#             path: /mnt/stateful_partition/kube-ephemeral-ssd/
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres # Sets service name
#   labels:
#     app: postgres # Labels and Selectors
# spec:
#   type: NodePort # Sets service type
#   ports:
#     - port: 5432 # Sets port to run the postgres application
#   selector:
#     app: postgres