apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: pgvector
      image: ankane/pgvector
      resources:
          limits:
            cpu: "4"
            memory: "16Gi"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secretpassword"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgvector/
      volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgredb
      persistentVolumeClaim:
       claimName: postgres-pvc