apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  # annotations:
    # cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP