apiVersion: v1
kind: Service
metadata:
  name: llama-2-70b-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: llama-2-70b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer