FROM python:3.10

WORKDIR /app
ENV HOSTNAME "localhost"
ENV PORT 7860
ENV MODEL_NAME "LLaMA 7B-Chat"

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 7860

CMD ["python", "app.py"]