apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mistral-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-mistral-7b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vllm-mistral-7b
    spec:
      containers:
      - name: vllm-mistral-7b
        image: vllm/vllm-openai:v0.2.3
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server", "--model", "mistralai/Mistral-7B-Instruct-v0.1", "--chat-template", "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token + ' ' }}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}"]
        resources:
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: "1"
        ports:
        - containerPort: 8000
        env:
        - name: HF_HOME
          value: /data
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: l4-demo
              key: HF_TOKEN
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
         - name: dshm
           emptyDir:
              medium: Memory
         - name: data
           ephemeral:
              volumeClaimTemplate:
                metadata:
                  labels:
                    type: data-volume
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: "premium-rwo"
                  resources:
                    requests:
                      storage: 200Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      