apiVersion: v1
kind: Pod
metadata:
  name: notebook-pod
spec:
  containers:
  - name: notebook-pod
    image: jupyter/base-notebook:x86_64-python-3.10
    ports:
      - containerPort: 8888
    resources:
      limits:
       nvidia.com/gpu: "2"
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-service
spec:
  selector:
    app: notebook-pod
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888