apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-7b-nf4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mistral-7b-nf4
  template:
    metadata:
      labels:
        app: mistral-7b-nf4
        server: text-generation-interface
    spec:
      containers:
      - name: mistral-7b-nf4
        image: ghcr.io/huggingface/text-generation-inference:1.1.0
        resources:
          limits:
            nvidia.com/gpu: "1"
        ports:
        - name: server-port
          containerPort: 8080
        env:
        - name: MODEL_ID
          value: mistralai/Mistral-7B-Instruct-v0.1
        - name: NUM_SHARD
          value: "1"
        - name: PORT 
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes-nf4
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: l4-demo
              key: HF_TOKEN
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
         - name: dshm
           emptyDir:
              medium: Memory
         - name: data
           ephemeral:
              volumeClaimTemplate:
                metadata:
                  labels:
                    type: data-volume
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: "premium-rwo"
                  resources:
                    requests:
                      storage: 200Gi
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
